AWSTemplateFormatVersion: 2010-09-09
Description: EC2LambdaTestDeploy102

Resources:
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow all traffic
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
        - IpProtocol: -1
          FromPort: 0
          ToPort: 65535
          CidrIpv6: '::/0'

  LambdaFullAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: LambdaFullAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'lambda:*'
                Resource: '*'

  EC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref LambdaFullAccessRole

  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      IamInstanceProfile: !Ref EC2InstanceProfile
      ImageId:  ami-039f5d5f278d91a6f
      SecurityGroupIds:
        - !Ref MySecurityGroup
      UserData: !Base64 |
          #!/bin/bash
          su - ubuntu -c "sudo -i -u ubuntu"
          su - ubuntu -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash"
          su - ubuntu -c "source ~/.nvm/nvm.sh && nvm install --lts"     
          cd /home/ubuntu/dist     
          su - ubuntu -c "source ~/.nvm/nvm.sh && cd ~/dist && npm install"
          su - ubuntu -c "source ~/.nvm/nvm.sh && cd ~/dist && npm run run-server-ec2"
      Tags:
        - Key: EC2LambdaTestDeploy
          Value: MyTag
